# This file is used for pulling Covalent images from ECR using docker-compose
# Example usage: Run "docker-compose --env-file .env.compose up" from the root of the project
# to pull the images from ECR and start the containers.

version: "3.9"

services:
  covalent-data:
    image: "public.ecr.aws/covalent/covalent_data"
    ports:
      - "80:8004"
    working_dir: /data
    networks:
      covalent:

  covalent-dispatcher:
    image: "public.ecr.aws/covalent/covalent_dispatcher"
    ports:
      - "80:8002"
    working_dir: /dispatcher
    networks:
      covalent:

  covalent-queuer:
    image: "public.ecr.aws/covalent/covalent_queuer"
    ports:
      - "80:8001"
    working_dir: /queuer
    networks:
      covalent:

  # Queue-consumer uses the same Dockerfile configurations as the Queuer
  covalent-queue-consumer:
    image: "public.ecr.aws/covalent/covalent_queuer"
    ports:
      - "80:8001"
    working_dir: /queuer
    networks:
      covalent:

  covalent-results:
    image: "public.ecr.aws/covalent/covalent_results"
    ports:
      - "80:8006"
    working_dir: /results
    networks:
      covalent:

  covalent-runner:
    image: "public.ecr.aws/covalent/covalent_runner"
    ports:
      - "80:8003"
    working_dir: /runner
    networks:
      covalent:

  covalent-ui:
    image: "public.ecr.aws/covalent/covalent_ui"
    ports:
      - "80:8004"
    working_dir: /ui_backend
    networks:
      covalent:

  covalent-nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      covalent:

networks:
  covalent:
