# This file is used for pulling Covalent images from ECR using docker-compose
# Example usage: Run "docker-compose --env-file .env.compose up" from the root of the project
# to pull the images from ECR and start the containers.

version: "3.9"

services:
  covalent-data:
    image: "${DATA_REPO}"
    command: sh -c "python main.py"
    ports:
      - "8004:8004"
    working_dir: /data
    networks:
     covalent:

  covalent-dispatcher:
    image: "${DISPATCHER_REPO}"
    command: sh -c "python main.py"
    ports:
      - "8002:8002"
    working_dir: /dispatcher
    networks:
     covalent:

  covalent-queuer:
    image: "${QUEUER_REPO}"
    command: sh -c "python main.py"
    ports:
      - "8001:8001"
    working_dir: /queuer
    networks:
      covalent:

  # Queue-consumer uses the same Dockerfile configurations as the Queuer
  covalent-queue-consumer:
    image: "${QUEUE_CONSUMER_REPO}"
    command: sh -c "python main.py"
    ports:
      - "3000:8001"
    working_dir: /queuer
    networks:
      covalent:

  covalent-results:
    image: "${RESULTS_REPO}"
    command: sh -c "python main.py"
    ports:
      - "8006:8006"
    working_dir: /results
    networks:
     covalent:

  covalent-runner:
    image: "${RUNNER_REPO}"
    command: sh -c "python main.py"
    ports:
      - "8003:8003"
    working_dir: /runner
    networks:
      covalent:

  covalent-ui:
    image: "${UI_REPO}"
    command: sh -c "python main.py"
    ports:
      - 3001:8004
      - 8005:8005
    environment:
      UI_SVC_HOST: 0.0.0.0
      UI_SVC_PORT: 8004
    working_dir: /ui_backend
    networks:
      covalent:

  covalent-nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      covalent:

networks:
  covalent:
