# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the GNU Affero General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

package:
  name: covalent
  version: {{ data.get('version') }}

source:
  - path: .
    folder: covalent

build:
  noarch: python
  script:
    - (cd ./covalent/covalent_ui/webapp && npm install && yarn build)
    - pip install ./covalent

requirements:
  build:
    - python
    - pip
    - nodejs
    - yarn
    {% for package in data.get('install_requires', []) -%}
    - {{ package }}
    {% endfor %}
  run:
    {% for package in resolved_packages('build') -%}
    - {{ package }}
    {% endfor %}

test:
  imports:
    - covalent
    - covalent_dispatcher
    - covalent_ui
  commands:
    - covalent status

about:
  home: {{ data.get('url') }}
  license: AGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - {{ data.get('maintainer') }}
  contact:
    - {{ data.get('author_email') }}
