# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the GNU Affero General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

package:
    name: covalent
    version: {{ data.get('version') }}

source:
    - path: .
      folder: cova
    - url: https://files.pythonhosted.org/packages/5b/78/0c8e4b41ee425be92888bc118af7c15fc7b771a7e495d7b48b223cd6c382/sentinel-0.3.0.tar.gz
      sha256: f28143aa4716dbc8f6193f5682176a3c33cd26aaae05d9ecf66c186a9887cc2d
      folder: sentinel
    - url: https://files.pythonhosted.org/packages/a9/d4/2f63aebfb1f284f359a7d035908b27378a32a0fc59a8fe57d1d4f27094e5/nats-py-2.0.0.tar.gz
      sha256: e983751199f38edad89eedc764d295f7359a2c0cc610d886e48e5a465b6a1ad1
      folder: nats-py
    - url: https://files.pythonhosted.org/packages/33/c9/854de19ff2b2a83111e892ef3028504a927f1aa19347de3f62abf38c2c99/aiolimiter-1.0.0.tar.gz
      sha256: 9d40767e4476048145dfa9f61948445168d6e63cf42c95785a20b9aaff2e4564
      folder: aiolimiter
    - url: https://files.pythonhosted.org/packages/67/a4/79a79ec12f315d18ace30d4fcb77e63b492be62a8e4bbc5f2dc0ddbf81b6/fastapi-socketio-0.0.9.tar.gz
      sha256: 8c73aa94fe1bf1c9964ff89233a6ba52eeeec3ac8b9de0024d9d82b11e46bde5
      folder: fastapi-socketio
      

build:
    script:
        - pip install ./sentinel
        - pip install ./cova
        - pip install ./nats-py
        - pip install ./aiolimiter
        - pip install ./fastapi-socketio
        - |
          cd ./cova/covalent_ui/webapp
          npm install
          yarn build

requirements:
    build:
        - python 3.8
        - pip
        - nodejs
        - yarn
        - poetry
        {% for package in data.get('install_requires', []) -%}
        {%   if not ( package.startswith('sentinel') or package.startswith('nats-py') or package.startswith('aiolimiter') or package.startswith('fastapi-socketio') ) -%}
        - {{ package }}
        {%   endif -%}
        {% endfor %}
    run:
        {% for package in resolved_packages('build') -%}
        - {{ package }}
        {% endfor %}

test:
    imports:
        - covalent
        - covalent_dispatcher
    commands:
        - covalent status

about:
    home: {{ data.get('url') }}
    license: AGPL
    license_file: LICENSE

extra:
    recipe-maintainers:
        - {{ data.get('maintainer') }}
    contact:
        - {{ data.get('author_email') }}
