openapi: 3.0.2
info:
  title: Queuer API
  version: 0.1.0
paths:
  /api/v0/submit/dispatch:
    post:
      tags:
        - submit
      summary: Submit Workflow
      description: Submit a workflow
      operationId: submit_workflow_api_v0_submit_dispatch_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResultPickle'
        required: true
      responses:
        '202':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ResultPickle:
      title: ResultPickle
      required:
        - result_object
      type: object
      properties:
        result_object:
          title: Result Object
          type: string
          format: binary
    SubmitResponse:
      title: SubmitResponse
      required:
        - dispatch_id
      type: object
      properties:
        dispatch_id:
          title: Dispatch Id
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
