name: 🐛 Bug report
description: Create a report to help us improve.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thank you for reporting! You may want to search the issues in this repository to see if this has already been reported or if others have encountered a similar problem. If you do find something similar, please comment on that issue instead of opening a new one. If this is a question, please post it in the Q&A section of [GitHub Discussions](https://github.com/AgnostiqHQ/covalent/discussions) instead of creating an issue.

  - type: textarea
    attributes:
      label: Environment
      description: For the version of Covalent, please give the actual version number (_e.g._ 0.18.3) if you are using a release version, or the first 7-8 characters of the commit hash if you have installed from `git`.
      # The trailing spaces on the following lines are to make filling the form
      # in easier.  The type is 'textarea' rather than three separate 'input's
      # to make the resulting issue body less noisy with headings.
      value: |
        - **Covalent version**: 
        - **Python version**: 
        - **Operating system**: 
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is happening?
      description: A short description of what is going wrong, in words.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce the issue?
      description: Give some steps that show the bug.  A [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) of code with output is best.  If you are copying in code, please remember to enclose it in triple backticks (` ``` [multiline code goes here] ``` `) so that it [displays correctly](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should happen?
      description: A short description, including about the expected output of any code in the previous section.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any suggestions?
      description: Not required, but if you have suggestions for how a contributor should fix this, or any problems we should be aware of, let us know.
    validations:
      required: false
