# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the GNU Affero General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

"""Uniformize MetaAsset links

Revision ID: 53cd9661c577
Revises: 305e512a5a08
Create Date: 2023-03-17 23:11:48.976448

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
# pragma: allowlist nextline secret
revision = "53cd9661c577"
# pragma: allowlist nextline secret
down_revision = "305e512a5a08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("electron_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("meta_record_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "electrons", ["meta_record_id"], ["id"])
        batch_op.drop_column("electron_id")

    with op.batch_alter_table("electron_dependency", schema=None) as batch_op:
        batch_op.create_foreign_key("electron_link", "electrons", ["parent_electron_id"], ["id"])

    with op.batch_alter_table("lattice_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("meta_record_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "lattices", ["meta_record_id"], ["id"])
        batch_op.drop_column("lattice_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lattice_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lattice_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "lattices", ["lattice_id"], ["id"])
        batch_op.drop_column("meta_record_id")

    with op.batch_alter_table("electron_dependency", schema=None) as batch_op:
        batch_op.drop_constraint("electron_link", type_="foreignkey")

    with op.batch_alter_table("electron_assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("electron_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "electrons", ["electron_id"], ["id"])
        batch_op.drop_column("meta_record_id")

    # ### end Alembic commands ###
