"""v13

Revision ID: 97202f5f47cb
Revises: 26d71848a404
Create Date: 2022-10-16 13:00:13.554644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
# pragma: allowlist nextline secret
revision = "97202f5f47cb"
# pragma: allowlist nextline secret
down_revision = "26d71848a404"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("electrons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_filename", sa.Text(), nullable=True))
        batch_op.drop_column("info_filename")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("electrons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("info_filename", sa.TEXT(), nullable=True))
        batch_op.drop_column("error_filename")

    # ### end Alembic commands ###
