"""Added dispatch_name to the lattice table

Revision ID: a5190277449b
Revises: 9b9d58f02985
Create Date: 2022-08-18 12:45:38.512778

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
# pragma: allowlist nextline secret
revision = "a5190277449b"
# pragma: allowlist nextline secret
down_revision = "9b9d58f02985"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lattices", sa.Column("dispatch_name", sa.Text(), nullable=True))
    op.execute("UPDATE lattices SET dispatch_name = name WHERE dispatch_name IS NULL")
    op.alter_column("lattices", sa.Column("dispatch_name", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lattices", "dispatch_name")
    # ### end Alembic commands ###
