openapi: 3.0.2
info:
  title: Covalent UI Backend Service API
  version: 0.1.0
paths:
  /api/v0/ui/workflow/{dispatch_id}/task/{task_id}:
    put:
      tags:
        - UI
      summary: Update Ui
      description: API Endpoint (/api/workflow/task) to update ui frontend
      operationId: update_ui_api_v0_ui_workflow__dispatch_id__task__task_id__put
      parameters:
        - required: true
          schema:
            title: Dispatch Id
            type: string
          name: dispatch_id
          in: path
        - required: true
          schema:
            title: Task Id
            type: integer
          name: task_id
          in: path
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateUIResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /api/v0/ui/workflow/draft:
    post:
      tags:
        - UI
      summary: Draw Draft
      description: "API Endpoint (/api/workflow/draft) to draw workflow draft "
      operationId: draw_draft_api_v0_ui_workflow_draft_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrawRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateUIResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    DrawRequest:
      title: DrawRequest
      required:
        - payload
      type: object
      properties:
        payload:
          title: Payload
          type: object
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    UpdateUIResponse:
      title: UpdateUIResponse
      required:
        - response
      type: object
      properties:
        response:
          title: Response
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
