# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
# 
# Licensed under the GNU Affero General Public License 3.0 (the "License"). 
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any 
# modifications or derivative works of this file must retain this copyright 
# notice, and modified files must contain a notice indicating that they have 
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

name: conda

on:
  # TODO: remove this line
  push:
#  schedule:
#    - cron: "02 4 * * *"
      

jobs:
  conda:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Check out head
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Conda dependencies
        run: |
          conda install conda-build conda-verify anaconda-client

      - name: Create Conda environment
        run: conda create --name buildenv python=${{ matrix.python-version }}

      - name: Build package
        run: |
          $CONDA/bin/activate buildenv
          conda env list
          conda build --override-channels --output-folder ./ --python ${{ matrix.python-version }} .

      - name: Convert package
        run: conda convert --platform all ./linux-64/*.tar.bz2

#      - name: Upload packages
#        run: anaconda upload -t ${{ secrets.ANACONDA_TOKEN }} upload -u agnostiq -l beta --skip-existing ./{linux,osx,win}-*/*.tar.bz2
          
#      - name: Build conda package
#        run: |
#          conda install conda-build conda-verify anaconda-client
#          conda config --append channels conda-forge
#          conda create --name buildenv python=${{ matrix.python-version }}
#          $CONDA/bin/activate buildenv
#          conda build --override-channels --output-folder=./ --python=${{ matrix.python-version }} .
#          conda convert --platform all ./linux-64/*.tar.bz2
#          anaconda upload -t ${{ secrets.ANACONDA_TOKEN }} upload -u agnostiq -l beta --skip-existing ./{linux,osx,win}-*/*.tar.bz2

