name: dummy

on:
  pull_request:

jobs:
  benchmark:
    name: Benchmarks
    uses: AgnostiqHQ/covalent/.github/workflows/benchmark.yml@fix_benchmark_workflow
    secrets: inherit # pragma: allowlist secret
