# Copyright 2023 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the Apache License 2.0 (the "License"). A copy of the
# License may be obtained with this software package or at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Use of this file is prohibited except in compliance with the License.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: man_2_create_release

on:
  workflow_dispatch:
    inputs:
      check_push_to_master:
        type: boolean
        required: true
        default: true
        description: "WARNING: Make sure the `man_1_push_to_master` workflow has passed successfully before running this workflow.
        Uncheck this box if it has."
      branch_name:
        type: string
        required: true
        default: "master"
        description: "The name of the branch to create a release from, defaults to master."

permissions:
  id-token: write
  contents: read

jobs:
  create_release:
    name: Create a Prerelease
    uses: AgnostiqHQ/covalent/.github/workflows/release.yml@develop
    if: >
      !github.event.inputs.check_push_to_master
    with:
      prerelease: true
      prerelease_name: github.event.inputs.branch_name
    secrets: inherit # pragma: allowlist secret

  notify_slack:
    name: Notify on Slack
    needs:
      - create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Format Slack message
        run: |
          VERSION="$(cat ./VERSION)"
          SLACK_MSG=":rocket: Version $VERSION is now available."
          echo "SLACK_MSG=$SLACK_MSG" >> $GITHUB_ENV

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "covalent-ci"
          SLACK_USERNAME: "CovalentOpsBot"
          SLACK_MESSAGE: ${{ env.SLACK_MSG }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
